# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-09 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='models',
            new_name='mobile',
        ),
    ]
